#!/usr/bin/env rampart
/* rampart-ocr test suite.
 *
 * Exercises the PP-OCR pipeline end to end: detection (DB probability map ->
 * boxes), angle classification, recognition (CTC) and page assembly, plus the
 * cross-module binding -- rampart-ocr carries no ONNX Runtime and reaches
 * rampart-onnx's through the rp_onnx_sess_* C ABI.
 *
 * Pages come from test_docs/ beside this script (installed to
 * <prefix>/test/test_docs/).  They are public domain or generated by this
 * project; see test_docs/PROVENANCE.md for sources and the ground truth the
 * assertions below are drawn from.
 *
 * The models (~21 MB) are fetched on first use through rampart-models into
 * ~/.rampart/models/ocr/ppocr-v5/.  Decline the download and the model-dependent
 * sections print "- skipped".
 *
 *   rampart ocr-test.js
 */
rampart.globalize(rampart.utils);

/* locate rampart-ocr.so, in order:
   1) build/  2) build-cpu/  3) build-gpu/  4) build_cpu/  5) build_gpu/
   6) modules/            (e.g. when run from <prefix>/run_tests.sh)
   7) bare require        (installed / on rampart's module path)
   rampart-onnx must be beside it -- the module binds it at require() time. */
function loadModule() {
    var sp = process.scriptPath;
    var tries = [
        sp + '/build/rampart-ocr',
        sp + '/build-cpu/rampart-ocr',
        sp + '/build-gpu/rampart-ocr',
        sp + '/build_cpu/rampart-ocr',
        sp + '/build_gpu/rampart-ocr',
        sp + '/modules/rampart-ocr',
        'rampart-ocr'
    ];
    for (var i = 0; i < tries.length; i++) {
        try { return require(tries[i]); } catch(e) { var last = e; }
    }
    printf("ERROR: could not load rampart-ocr.so from any of:\n  %s\n", tries.join('\n  '));
    process.exit(1);
}
var ocr = loadModule();

/* rampart-models.js: beside this script in the source tree, or an installed
   module (modules/rampart-models.js) from the install tree. */
function loadModels() {
    var sp = process.scriptPath;
    try { return require(sp + '/rampart-models.js'); }
    catch (e) { try { return require('rampart-models'); } catch (e2) { return null; } }
}
var models = loadModels();

var DOCS = process.scriptPath + '/test_docs';

/* ================================================================
   test harness (same shape as onnx-test.js / llamacpp-test.js)
   ================================================================ */
var testnum = 0, failed = 0;

function testFeature(name, test) {
    var error = false;
    testnum++;
    if (typeof test == 'function') {
        try { test = test(); }
        catch(e) { error = e; test = false; }
    }
    printf("testing ocr - %3d - %-60s - ", testnum, name);
    fflush(stdout);
    if (test) {
        printf("passed\n");
    } else {
        printf(">>>>> FAILED <<<<<\n");
        failed++;
        if (error) console.log(error);
    }
}

/* ================================================================
   helpers
   ================================================================ */
function has(p) { return !!stat(p); }

/* stdin/stdout are bare globals in current rampart; older builds expose them
   on rampart.utils only */
var STDIN  = (typeof stdin  !== 'undefined') ? stdin  : rampart.utils.stdin;
var STDOUT = (typeof stdout !== 'undefined') ? stdout : rampart.utils.stdout;

function ask(question) {
    printf("%s", question);
    fflush(STDOUT);
    var a = fgets(STDIN, 255);
    return a ? a.trim().toLowerCase() : '';
}

/* Locate the PP-OCR model set, fetching it if absent.  Returns
   {dir,det,rec,cls,dict} or null (missing rampart-models, declined, or failed),
   in which case the model-dependent sections are skipped. */
function obtainModels() {
    if (!models) { printf("  rampart-models.js not found; skipping\n"); return null; }
    try {
        return models.ocrGet('ppocr-v5', {
            confirm: function(info) {
                var r = ask(sprintf("  PP-OCR models (%s) are needed for the OCR tests.\n" +
                                    "  Download to %s? [y/N]: ", info.size, info.dest));
                return r === 'y' || r === 'yes';
            }
        });
    } catch(e) {
        printf("  model fetch failed: %s\n", e.message || e);
        return null;
    }
}

/* Whitespace-insensitive containment.  OCR legitimately disagrees about
   spacing -- wide typewriter tracking makes "TECHNICAL NOTE" come back as
   "TECHNICALNOTE" -- so assertions compare with all spaces removed.  Anything
   stricter tests the font's tracking rather than the recognizer. */
function squash(s) { return String(s).replace(/\s+/g, '').toUpperCase(); }
function contains(hay, needle) { return squash(hay).indexOf(squash(needle)) !== -1; }

/* how many of `list` appear in the page text */
function foundCount(text, list) {
    var n = 0;
    list.forEach(function(s){ if (contains(text, s)) n++; });
    return n;
}

/* ================================================================
   Test: module + binding
   ================================================================ */
testFeature("module loads", typeof ocr === 'object' && ocr !== null);
testFeature("init exists",       typeof ocr.init       === 'function');
testFeature("modelInfo exists",  typeof ocr.modelInfo  === 'function');
testFeature("runtimeInfo exists",typeof ocr.runtimeInfo === 'function');

var RI = null;
testFeature("bound to rampart-onnx's engine (no ORT of its own)", function() {
    RI = ocr.runtimeInfo();
    return RI && typeof RI.ort === 'string' && RI.ort.length > 0;
});
testFeature("session ABI agreed between the two modules", function() {
    return RI && RI.sessionAbi >= 1;
});

var MODELS = obtainModels();
if (RI) printf("       ORT %s | runtime: %s | CUDA: %s\n", RI.ort, RI.runtime, RI.cuda ? "yes" : "no");

/* ================================================================
   Test: model introspection (also documents PP-OCR's tensor shapes)
   ================================================================ */
function runModelInfoTest() {
    printf("\n--- model shapes (modelInfo) ---\n");
    if (!MODELS) { printf("- skipped\n"); return; }

    var det = null, rec = null;
    testFeature("det model: 1 input, probability-map output", function() {
        det = ocr.modelInfo(MODELS.det);
        return det.inputs.length === 1 && det.outputs.length >= 1 &&
               det.inputs[0].type === 'float32' && det.inputs[0].shape.length === 4;
    });
    testFeature("rec model: CTC logits, last dim = class count", function() {
        rec = ocr.modelInfo(MODELS.rec);
        return rec.outputs.length >= 1 && rec.outputs[0].shape.length === 3 &&
               rec.outputs[0].shape[2] > 1000;
    });
    /* PP-OCR's class list is blank + dictionary + space, so the model's class
       count must be the dictionary's line count + 2.  This is the off-by-one
       that silently shifts every decoded character, so assert it explicitly. */
    testFeature("class count == dictionary lines + 2 (blank + dict + space)", function() {
        var lines = readFile(MODELS.dict, true).split('\n');
        /* trailing newline yields a final empty element; CRLF handled by trim */
        while (lines.length && lines[lines.length-1].replace(/[\r\n]/g,'') === '') lines.pop();
        return rec.outputs[0].shape[2] === lines.length + 2;
    });
}

/* ================================================================
   Test: detection only (probability map)
   ================================================================ */
function runDetectTest() {
    printf("\n--- detection (probability map) ---\n");
    if (!MODELS || !has(DOCS + '/synthetic-memo.png')) { printf("- skipped\n"); return; }

    var p = null;
    testFeature("detProbe returns a map sized to a multiple of 32", function() {
        p = ocr.detProbe(DOCS + '/synthetic-memo.png', MODELS.det);
        return p.netW % 32 === 0 && p.netH % 32 === 0 && p.mapW > 0 && p.mapH > 0;
    });
    testFeature("probabilities are in [0,1]", function() {
        return p.min >= 0 && p.max <= 1 && p.max > 0.5;
    });
    /* A page of text is mostly background: a foreground fraction near 0 means
       detection found nothing, near 1 means it fired everywhere. */
    testFeature("foreground fraction is plausible for a text page", function() {
        return p.fgFrac > 0.001 && p.fgFrac < 0.5;
    });
    testFeature("back-scale factors are per-axis and positive", function() {
        return p.sx > 0 && p.sy > 0;
    });
}

/* ================================================================
   Test: full page on the synthetic memo (EXACT ground truth)
   ================================================================ */
var handle = null;

function runSyntheticTest() {
    printf("\n--- full page: synthetic memo (exact ground truth) ---\n");
    if (!MODELS || !has(DOCS + '/synthetic-memo.png')) { printf("- skipped\n"); return; }

    var r = null;
    testFeature("init + page", function() {
        handle = ocr.init(Object.assign({ threads: 0 }, MODELS));
        r = handle.readText(DOCS + '/synthetic-memo.png');
        return r && typeof r.text === 'string' && Array.isArray(r.lines);
    });
    if (!r) return;

    testFeature("found a plausible number of lines", r.lines.length >= 8 && r.lines.length <= 20);
    testFeature("heading recognized", contains(r.text, "RAMPART LANGTOOLS TEST DOCUMENT"));
    testFeature("pangram 1 recognized", contains(r.text, "The quick brown fox jumps over the lazy dog"));
    testFeature("pangram 2 recognized", contains(r.text, "Pack my box with five dozen liquor jugs"));
    testFeature("digits recognized", contains(r.text, "0123456789"));
    /* the isolated footer stamp: far from every other line, which is what makes
       it a real test of detection rather than of a big text block */
    testFeature("isolated Bates-style stamp recognized", contains(r.text, "RAMPART-OCR-000001"));
    testFeature("currency amount recognized", contains(r.text, "1,250.00 USD"));

    testFeature("every line carries a confidence in [0,1]", function() {
        return r.lines.every(function(l){ return l.score >= 0 && l.score <= 1; });
    });
    testFeature("most lines are confident (>0.8)", function() {
        var good = r.lines.filter(function(l){ return l.score > 0.8; }).length;
        return good >= r.lines.length * 0.8;
    });

    /* geometry: 4 corners = 8 numbers, inside the page */
    testFeature("boxes are 4 corners within the image bounds", function() {
        return r.lines.every(function(l){
            if (!Array.isArray(l.box) || l.box.length !== 8) return false;
            for (var i = 0; i < 8; i += 2)
                if (l.box[i] < 0 || l.box[i] > 1275 || l.box[i+1] < 0 || l.box[i+1] > 1650) return false;
            return true;
        });
    });
    /* reading order: the heading sits above the footer stamp */
    testFeature("lines come back in reading order (top to bottom)", function() {
        var hi = -1, si = -1, i;
        for (i = 0; i < r.lines.length; i++) {
            if (hi < 0 && contains(r.lines[i].text, "RAMPART LANGTOOLS TEST")) hi = i;
            if (si < 0 && contains(r.lines[i].text, "RAMPART-OCR-000001")) si = i;
        }
        return hi >= 0 && si >= 0 && hi < si;
    });
}

/* ================================================================
   Test: angle classification (the same page, upside down)
   ================================================================ */
function runRotatedTest() {
    printf("\n--- angle classification (180-degree page) ---\n");
    if (!handle || !has(DOCS + '/synthetic-memo-rot180.png')) { printf("- skipped\n"); return; }

    var r = null;
    testFeature("page() on an upside-down scan", function() {
        r = handle.readText(DOCS + '/synthetic-memo-rot180.png');
        return r && Array.isArray(r.lines) && r.lines.length > 5;
    });
    if (!r) return;

    /* Without angle classification these lines decode to noise; with it they
       come back verbatim.  The BOX order still follows the image as given
       (the footer is physically at the top of a rotated page), which matches
       PP-OCR: cls rotates the crop for reading, it does not re-lay-out. */
    testFeature("upside-down heading still recognized", contains(r.text, "RAMPART LANGTOOLS TEST DOCUMENT"));
    testFeature("upside-down pangram still recognized", contains(r.text, "The quick brown fox jumps over the lazy dog"));
    testFeature("upside-down stamp still recognized", contains(r.text, "RAMPART-OCR-000001"));
}

/* ================================================================
   Test: real scanned typescript (NASA Technical Note D-1766)
   ================================================================ */
function runScanTest() {
    printf("\n--- real scan: NASA typescript ---\n");
    if (!handle || !has(DOCS + '/nasa-tn-d1766-p2.jpg')) { printf("- skipped\n"); return; }

    var r = null;
    testFeature("page() on a real 1963 scan", function() {
        r = handle.readText(DOCS + '/nasa-tn-d1766-p2.jpg');
        return r && r.lines.length > 15;
    });
    if (!r) return;

    testFeature("agency name recognized", contains(r.text, "NATIONAL AERONAUTICS AND SPACE ADMINISTRATION"));
    testFeature("report number recognized", contains(r.text, "TECHNICAL NOTE D-1766"));
    testFeature("authors recognized", contains(r.text, "Kenneth W. Mort"));
    testFeature("section headings recognized", function() {
        return contains(r.text, "SUMMARY") && contains(r.text, "INTRODUCTION");
    });
    /* Body prose is where a scanned typescript is really tested. */
    testFeature("body prose recognized", function() {
        return contains(r.text, "The vertical or near-vertical descent of propeller-driven");
    });
    /* The source PDF ships a legacy OCR layer that renders this word
       "ADMINISTMTION" and spaces out "v e r t i c a l".  Beating it is the
       entire justification for this module over what the corpus already has. */
    testFeature("beats the PDF's own legacy OCR layer", function() {
        return contains(r.text, "ADMINISTRATION") && !contains(r.text, "ADMINISTMTION");
    });
}

/* ================================================================
   Test: dense historical newsprint (the hard case)
   ================================================================ */
function runNewsprintTest() {
    printf("\n--- real scan: 1918 newsprint (dense, multi-column) ---\n");
    if (!handle || !has(DOCS + '/nytimes-1918-p1-top.jpg')) { printf("- skipped\n"); return; }

    var r = null;
    testFeature("page() on dense newsprint", function() {
        r = handle.readText(DOCS + '/nytimes-1918-p1-top.jpg');
        return r && r.lines.length > 10;
    });
    if (!r) return;

    /* The display headlines are large and clean: any working OCR must get
       these, so they are asserted. */
    var heads = [
        "ARMISTICE SIGNED, END OF THE WAR!",
        "BERLIN SEIZED BY REVOLUTIONISTS",
        "NEW CHANCELLOR BEGS FOR ORDER",
        "OUSTED KAISER FLEES TO HOLLAND"
    ];
    testFeature("all four display headlines recognized", foundCount(r.text, heads) === 4);
    testFeature("dateline recognized", contains(r.text, "NEW YORK, MONDAY, NOVEMBER 11, 1918"));
    testFeature("slogan recognized", contains(r.text, "All the News That's"));

    /* The blackletter masthead is deliberately NOT asserted: PP-OCR is trained
       on modern faces and mangles it ("@be New ork @imes").  Reported so a
       future model improvement is visible, but a failure here would be
       measuring the font, not the module. */
    printf("       masthead (blackletter, not asserted): %s\n",
           (r.lines[0] && r.lines[0].text) ? r.lines[0].text : "(none)");

    /* Misreads of small/damaged type should be marked as such, which is what
       makes the confidence useful for filtering downstream. */
    testFeature("low-confidence reads are flagged, not silently trusted", function() {
        var lo = r.lines.filter(function(l){ return l.score < 0.7; });
        var hi = r.lines.filter(function(l){ return l.score > 0.9; });
        return hi.length > lo.length;
    });
}

/* ================================================================
   Test: input forms + lifecycle
   ================================================================ */
function runApiTest() {
    printf("\n--- input forms and lifecycle ---\n");
    if (!handle || !has(DOCS + '/synthetic-memo.png')) { printf("- skipped\n"); return; }

    testFeature("page() accepts a Buffer as well as a path", function() {
        var buf = readFile(DOCS + '/synthetic-memo.png');
        var r = handle.readText(buf);
        return r && contains(r.text, "RAMPART LANGTOOLS TEST DOCUMENT");
    });
    testFeature("a bad path throws rather than returning empty", function() {
        try { handle.readText(DOCS + '/does-not-exist.png'); return false; }
        catch(e) { return /cannot open|decode/i.test(e.message); }
    });
    testFeature("errMsg is clean after a good call", function() {
        handle.readText(DOCS + '/synthetic-memo.png');
        return handle.errMsg === undefined;
    });
    testFeature("destroy()", function() { handle.destroy(); return true; });
    testFeature("use after destroy throws", function() {
        try { handle.readText(DOCS + '/synthetic-memo.png'); return false; }
        catch(e) { return /destroy/i.test(e.message); }
    });
    testFeature("wrong dictionary is rejected at init", function() {
        if (!MODELS) return true;
        try {
            ocr.init({ det: MODELS.det, rec: MODELS.rec, dict: DOCS + '/PROVENANCE.md' });
            return false;
        } catch(e) { return /dictionary/i.test(e.message); }
    });
}

/* ================================================================
   run
   ================================================================ */
runModelInfoTest();
runDetectTest();
runSyntheticTest();
runRotatedTest();
runScanTest();
runNewsprintTest();
runApiTest();

printf("\nocr: %d tests run, %d failed\n", testnum, failed);
process.exit(failed ? 1 : 0);
